version: "3.8"
services:
  web:
    depends_on:
      - db
    build: ./
    ports:
      - "80:3000"
    restart: always
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: newtab
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
