version: "3.8"
services:
  web:
    depends_on:
      - db
    build: ./
    ports:
      - "80:3000"
    restart: always
    volumes:
      - persistant:/app/data
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "newtab"
      #MYSQL_USER: "root"
      #MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - db:/var/lib/mysql

volumes:
  persistant:
  db:
